/// <reference types="nativewind/types" />
export type RootStackParamList = {
    Splash: undefined;
    Home: undefined;
  };
  
  export type SplashScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Splash'>;

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.